name: Github CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0

  py-tests:
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        test-type: ["unittests"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_HOME=${POETRY_HOME} python - --version 1.2.0
        poetry --version
        python -c "import sys; print(f'Running test with py version: {sys.version}')"
        poetry export --with dev --with tests --output requirements.txt --without-hashes
        pip install -r requirements.txt
    - name: Run pytests
      run: |
        python -m pytest -k ${TEST_TYPE} -vvv --cov --junitxml=${TEST_TYPE}.xml
      env:
        POETRY_HOME: /opt/poetry
        PATH: $POETRY_HOME/bin/:$PATH
        TEST_TYPE: ${{ matrix.test-type }}
